services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tutor_pass
      MYSQL_DATABASE: 'tutor_db'
    ports:
      - '3306:3306'
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080